version: '3.8'

services:
  # 1. Broker MQTT (O Carteiro)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: heartbox-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  # 2. Node-RED (O Cérebro / API)
  nodered:
    image: nodered/node-red:latest
    container_name: heartbox-nodered
    ports:
      - "1880:1880"
    restart: unless-stopped

  # 3. InfluxDB v1.x (O Cofre de Histórico)
  influxdb:
    image: influxdb:1.8
    container_name: heartbox-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=heartbox
    restart: unless-stopped

  # 4. Grafana (A Vitrine Visual)
  grafana:
    image: grafana/grafana:latest
    container_name: heartbox-grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: unless-stopped